### ISSUE TITLE
Fix base64 regex

### ISSUE THREAD

**Issue by edoardottt** [hahwul/RegexPassive#2]
The base64 regex shouldn't be like this one `[A-Za-z0-9+\/]{15,}(={0,2})` ?

Because the one in the repo now (`([A-Za-z0-9+\/]{15,}=+)`) is saying that a `=` is mandatory.. like one or more equal sign, but I'm pretty sure there can be 0, 1 or 2.

**Comment by hahwul** [comment]
Hi @edoardottt 
Agree! this regular expression cannot identify all base64 case. However, if I allow all the cases open, there will be a lot of false positive... so is there a good way? 😭

**Comment by edoardottt** [comment]
Damn, you're right.. Honestly I don't know, but maybe yours is the best balance between true/false positive.

**Comment by hahwul** [comment]
@edoardottt 
Um, Then I think it would be good to just show all the regular expressions for base64. 
The choice is up to the user 😆 I'll add several examples first! 
Thank you very much for your opinion!

**Comment by edoardottt** [comment]
Ok...it seems the best option!  
If it can be useful, I use this one for base64-encoded JSON: `ey[A-Za-z0-9+\/]{20,}(={0,2})`

**Comment by hahwul** [comment]
@edoardottt 
I'll collect various cases in similar format! 

![스크린샷 2022-04-02 오후 5 11 29](https://user-images.githubusercontent.com/13212227/161373799-5cc76b96-6cdb-42ab-b59e-d26d86e86b56.png)

Thank you so very much :D
